// Giulia Giozza, 2022


#include <stdio.h>
#include <stdlib.h>

int yylex();
extern char *yytext;
extern FILE *yyin;

int isRunning(void);
void initMe(void);

int main(int argc, char **argv){

	int token = 0;

	if (argc < 2){
		fprintf(stderr, "Call should be: ./a.out <input file name>\n");
		exit(1);
	} 

	yyin = fopen(argv[1], "r");
	if(yyin == 0){ // file pointer for analyzer generated by lex
		fprintf(stderr, "File %s couldn`t be opened.\n", argv[1]);
        exit(2);
	}

	initMe();

	while(isRunning()){
		token = yylex();

		if(!isRunning()){ // workaround for EOF error
			break;
		}

		printf("LINE: %d \t TOKEN: %d \t CONTEÚDO: %s\n", getLineNumber(), token, yytext);
	}
	
	hashPrint();
	exit(0);
}