// Giulia Giozza, 2022


#include <stdio.h>
#include <stdlib.h>

extern FILE *yyin;

int main(int argc, char **argv){

	int token = 0;

	if (argc < 2){
		fprintf(stderr, "Call should be: ./etapa2 <input file name>\n");
		exit(1);
	} 

	yyin = fopen(argv[1], "r");
	if(yyin == 0){ // file pointer for analyzer generated by lex
		fprintf(stderr, "File %s couldn`t be opened.\n", argv[1]);
        exit(2);
	}

	hashInit();

    yyparse();
	
	printf("Finishing with success. \n");
	exit(0);
}